# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BiosTool.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BiosTool(object):
    def setupUi(self, BiosTool):
        BiosTool.setObjectName("BiosTool")
        BiosTool.resize(1028, 699)
        font = QtGui.QFont()
        font.setPointSize(10)
        BiosTool.setFont(font)
        self.Gset_Analysis = QtWidgets.QTabWidget(BiosTool)
        self.Gset_Analysis.setGeometry(QtCore.QRect(16, 19, 821, 641))
        self.Gset_Analysis.setObjectName("Gset_Analysis")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 471, 261))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.logfile_name = QtWidgets.QLineEdit(self.groupBox)
        self.logfile_name.setObjectName("logfile_name")
        self.gridLayout.addWidget(self.logfile_name, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.file_browser = QtWidgets.QPushButton(self.groupBox)
        self.file_browser.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/loupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_browser.setIcon(icon)
        self.file_browser.setIconSize(QtCore.QSize(50, 50))
        self.file_browser.setObjectName("file_browser")
        self.gridLayout.addWidget(self.file_browser, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.root_path = QtWidgets.QLineEdit(self.groupBox)
        self.root_path.setObjectName("root_path")
        self.gridLayout.addWidget(self.root_path, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.folder_browser = QtWidgets.QPushButton(self.groupBox)
        self.folder_browser.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/search_query_128px_1063400_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folder_browser.setIcon(icon1)
        self.folder_browser.setIconSize(QtCore.QSize(50, 50))
        self.folder_browser.setObjectName("folder_browser")
        self.gridLayout.addWidget(self.folder_browser, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 1, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 1, 1, 1)
        self.Execute = QtWidgets.QGroupBox(self.tab)
        self.Execute.setGeometry(QtCore.QRect(9, 289, 481, 274))
        self.Execute.setObjectName("Execute")
        self.label_3 = QtWidgets.QLabel(self.Execute)
        self.label_3.setGeometry(QtCore.QRect(10, 46, 211, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.e_refresh_guid_template = QtWidgets.QPushButton(self.Execute)
        self.e_refresh_guid_template.setGeometry(QtCore.QRect(400, 26, 62, 58))
        self.e_refresh_guid_template.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/cloud-computing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e_refresh_guid_template.setIcon(icon2)
        self.e_refresh_guid_template.setIconSize(QtCore.QSize(50, 50))
        self.e_refresh_guid_template.setObjectName("e_refresh_guid_template")
        self.label_4 = QtWidgets.QLabel(self.Execute)
        self.label_4.setGeometry(QtCore.QRect(10, 123, 191, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.e_replace_logfile_guid = QtWidgets.QPushButton(self.Execute)
        self.e_replace_logfile_guid.setGeometry(QtCore.QRect(400, 103, 62, 58))
        self.e_replace_logfile_guid.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/exchange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e_replace_logfile_guid.setIcon(icon3)
        self.e_replace_logfile_guid.setIconSize(QtCore.QSize(50, 50))
        self.e_replace_logfile_guid.setObjectName("e_replace_logfile_guid")
        self.label_5 = QtWidgets.QLabel(self.Execute)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 311, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.e_produce_driver_loading_sequence = QtWidgets.QPushButton(self.Execute)
        self.e_produce_driver_loading_sequence.setGeometry(QtCore.QRect(400, 180, 62, 58))
        self.e_produce_driver_loading_sequence.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/timeline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e_produce_driver_loading_sequence.setIcon(icon4)
        self.e_produce_driver_loading_sequence.setIconSize(QtCore.QSize(50, 50))
        self.e_produce_driver_loading_sequence.setObjectName("e_produce_driver_loading_sequence")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(500, 300, 256, 261))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(820, 9, 256, 274))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(500, 20, 251, 261))
        self.pushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/cat-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setIconSize(QtCore.QSize(400, 400))
        self.pushButton.setObjectName("pushButton")
        self.Gset_Analysis.addTab(self.tab, "")
        self.Gset = QtWidgets.QWidget()
        self.Gset.setObjectName("Gset")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Gset)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 30, 481, 261))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.root_path_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.root_path_2.setObjectName("root_path_2")
        self.gridLayout_2.addWidget(self.root_path_2, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 3, 1, 1)
        self.root_path_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.root_path_3.setObjectName("root_path_3")
        self.gridLayout_2.addWidget(self.root_path_3, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.folder_browser_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.folder_browser_3.setText("")
        self.folder_browser_3.setIcon(icon1)
        self.folder_browser_3.setIconSize(QtCore.QSize(50, 50))
        self.folder_browser_3.setObjectName("folder_browser_3")
        self.gridLayout_2.addWidget(self.folder_browser_3, 1, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 1, 1, 1)
        self.folder_browser_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.folder_browser_2.setText("")
        self.folder_browser_2.setIcon(icon1)
        self.folder_browser_2.setIconSize(QtCore.QSize(50, 50))
        self.folder_browser_2.setObjectName("folder_browser_2")
        self.gridLayout_2.addWidget(self.folder_browser_2, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 2, 3, 1, 1)
        self.root_path_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.root_path_4.setObjectName("root_path_4")
        self.gridLayout_2.addWidget(self.root_path_4, 2, 2, 1, 1)
        self.folder_browser_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.folder_browser_4.setText("")
        self.folder_browser_4.setIcon(icon1)
        self.folder_browser_4.setIconSize(QtCore.QSize(50, 50))
        self.folder_browser_4.setObjectName("folder_browser_4")
        self.gridLayout_2.addWidget(self.folder_browser_4, 2, 5, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.Gset)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(540, 310, 251, 261))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.Execute_2 = QtWidgets.QGroupBox(self.Gset)
        self.Execute_2.setGeometry(QtCore.QRect(30, 433, 481, 141))
        self.Execute_2.setObjectName("Execute_2")
        self.label_6 = QtWidgets.QLabel(self.Execute_2)
        self.label_6.setGeometry(QtCore.QRect(10, 46, 281, 31))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.e_produce_gset_items_excel = QtWidgets.QPushButton(self.Execute_2)
        self.e_produce_gset_items_excel.setGeometry(QtCore.QRect(410, 30, 62, 58))
        self.e_produce_gset_items_excel.setText("")
        self.e_produce_gset_items_excel.setIcon(icon4)
        self.e_produce_gset_items_excel.setIconSize(QtCore.QSize(50, 50))
        self.e_produce_gset_items_excel.setObjectName("e_produce_gset_items_excel")
        self.pushButton_2 = QtWidgets.QPushButton(self.Gset)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 40, 251, 251))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(400, 400))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Gset)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 290, 481, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.root_path_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.root_path_5.setGeometry(QtCore.QRect(210, 90, 161, 30))
        self.root_path_5.setObjectName("root_path_5")
        self.folder_browser_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.folder_browser_5.setGeometry(QtCore.QRect(410, 80, 62, 52))
        self.folder_browser_5.setText("")
        self.folder_browser_5.setIcon(icon1)
        self.folder_browser_5.setIconSize(QtCore.QSize(50, 50))
        self.folder_browser_5.setObjectName("folder_browser_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(30, 80, 151, 41))
        self.label_10.setObjectName("label_10")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 271, 28))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.Gset_Analysis.addTab(self.Gset, "")
        self.label_2.setBuddy(self.logfile_name)
        self.label.setBuddy(self.root_path)
        self.label_3.setBuddy(self.e_refresh_guid_template)
        self.label_4.setBuddy(self.e_replace_logfile_guid)
        self.label_5.setBuddy(self.e_produce_driver_loading_sequence)
        self.label_8.setBuddy(self.root_path)
        self.label_9.setBuddy(self.root_path)
        self.label_7.setBuddy(self.root_path)
        self.label_6.setBuddy(self.e_refresh_guid_template)
        self.label_10.setBuddy(self.root_path)

        self.retranslateUi(BiosTool)
        self.Gset_Analysis.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BiosTool)
        BiosTool.setTabOrder(self.root_path, self.folder_browser)
        BiosTool.setTabOrder(self.folder_browser, self.logfile_name)
        BiosTool.setTabOrder(self.logfile_name, self.file_browser)
        BiosTool.setTabOrder(self.file_browser, self.e_refresh_guid_template)
        BiosTool.setTabOrder(self.e_refresh_guid_template, self.e_replace_logfile_guid)
        BiosTool.setTabOrder(self.e_replace_logfile_guid, self.e_produce_driver_loading_sequence)
        BiosTool.setTabOrder(self.e_produce_driver_loading_sequence, self.pushButton)
        BiosTool.setTabOrder(self.pushButton, self.plainTextEdit)
        BiosTool.setTabOrder(self.plainTextEdit, self.root_path_2)
        BiosTool.setTabOrder(self.root_path_2, self.folder_browser_2)
        BiosTool.setTabOrder(self.folder_browser_2, self.root_path_3)
        BiosTool.setTabOrder(self.root_path_3, self.folder_browser_3)
        BiosTool.setTabOrder(self.folder_browser_3, self.root_path_4)
        BiosTool.setTabOrder(self.root_path_4, self.folder_browser_4)
        BiosTool.setTabOrder(self.folder_browser_4, self.checkBox)
        BiosTool.setTabOrder(self.checkBox, self.root_path_5)
        BiosTool.setTabOrder(self.root_path_5, self.folder_browser_5)
        BiosTool.setTabOrder(self.folder_browser_5, self.e_produce_gset_items_excel)
        BiosTool.setTabOrder(self.e_produce_gset_items_excel, self.pushButton_2)
        BiosTool.setTabOrder(self.pushButton_2, self.plainTextEdit_2)
        BiosTool.setTabOrder(self.plainTextEdit_2, self.Gset_Analysis)

    def retranslateUi(self, BiosTool):
        _translate = QtCore.QCoreApplication.translate
        BiosTool.setWindowTitle(_translate("BiosTool", "BiosTool"))
        self.groupBox.setTitle(_translate("BiosTool", "Input"))
        self.label_2.setText(_translate("BiosTool", "POST LogFile:"))
        self.logfile_name.setPlaceholderText(_translate("BiosTool", "LivingStone2.log"))
        self.root_path.setPlaceholderText(_translate("BiosTool", "project root path"))
        self.label.setText(_translate("BiosTool", "Project Location:"))
        self.Execute.setTitle(_translate("BiosTool", "Execute"))
        self.label_3.setText(_translate("BiosTool", "Refresh Guid Template"))
        self.label_4.setText(_translate("BiosTool", "Replace LogFile Guid"))
        self.label_5.setText(_translate("BiosTool", "Produce Driver Loading Sequence"))
        self.Gset_Analysis.setTabText(self.Gset_Analysis.indexOf(self.tab), _translate("BiosTool", "BIOS Logfile Analysis "))
        self.groupBox_2.setTitle(_translate("BiosTool", "Input"))
        self.root_path_2.setPlaceholderText(_translate("BiosTool", "c:\\LivingStone2"))
        self.root_path_3.setPlaceholderText(_translate("BiosTool", "c:\\LivingStone2\\OEMBOARD\\LivingStone2"))
        self.label_8.setText(_translate("BiosTool", "Platform Folder Location:"))
        self.label_9.setText(_translate("BiosTool", "Output Location:"))
        self.label_7.setText(_translate("BiosTool", "Source Code Location:"))
        self.root_path_4.setPlaceholderText(_translate("BiosTool", "c:\\temp"))
        self.Execute_2.setTitle(_translate("BiosTool", "Execute"))
        self.label_6.setText(_translate("BiosTool", "Produce Gset items Excel file "))
        self.groupBox_3.setTitle(_translate("BiosTool", "Setup Variable"))
        self.root_path_5.setPlaceholderText(_translate("BiosTool", "c:\\temp"))
        self.label_10.setText(_translate("BiosTool", "Input Location:"))
        self.checkBox.setText(_translate("BiosTool", "used runtime setup variable"))
        self.Gset_Analysis.setTabText(self.Gset_Analysis.indexOf(self.Gset), _translate("BiosTool", "Gset Analysis"))

